// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	time "time"

	models "github.com/es-debug/backend-academy-2024-go-template/internal/domain/models"
	mock "github.com/stretchr/testify/mock"
)

// EventMock is an autogenerated mock type for the Event type
type EventMock struct {
	mock.Mock
}

type EventMock_Expecter struct {
	mock *mock.Mock
}

func (_m *EventMock) EXPECT() *EventMock_Expecter {
	return &EventMock_Expecter{mock: &_m.Mock}
}

// GetBody provides a mock function with no fields
func (_m *EventMock) GetBody() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetBody")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// EventMock_GetBody_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBody'
type EventMock_GetBody_Call struct {
	*mock.Call
}

// GetBody is a helper method to define mock.On call
func (_e *EventMock_Expecter) GetBody() *EventMock_GetBody_Call {
	return &EventMock_GetBody_Call{Call: _e.mock.On("GetBody")}
}

func (_c *EventMock_GetBody_Call) Run(run func()) *EventMock_GetBody_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *EventMock_GetBody_Call) Return(_a0 string) *EventMock_GetBody_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *EventMock_GetBody_Call) RunAndReturn(run func() string) *EventMock_GetBody_Call {
	_c.Call.Return(run)
	return _c
}

// GetCreatedAt provides a mock function with no fields
func (_m *EventMock) GetCreatedAt() time.Time {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetCreatedAt")
	}

	var r0 time.Time
	if rf, ok := ret.Get(0).(func() time.Time); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(time.Time)
	}

	return r0
}

// EventMock_GetCreatedAt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCreatedAt'
type EventMock_GetCreatedAt_Call struct {
	*mock.Call
}

// GetCreatedAt is a helper method to define mock.On call
func (_e *EventMock_Expecter) GetCreatedAt() *EventMock_GetCreatedAt_Call {
	return &EventMock_GetCreatedAt_Call{Call: _e.mock.On("GetCreatedAt")}
}

func (_c *EventMock_GetCreatedAt_Call) Run(run func()) *EventMock_GetCreatedAt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *EventMock_GetCreatedAt_Call) Return(_a0 time.Time) *EventMock_GetCreatedAt_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *EventMock_GetCreatedAt_Call) RunAndReturn(run func() time.Time) *EventMock_GetCreatedAt_Call {
	_c.Call.Return(run)
	return _c
}

// GetTitle provides a mock function with no fields
func (_m *EventMock) GetTitle() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetTitle")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// EventMock_GetTitle_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTitle'
type EventMock_GetTitle_Call struct {
	*mock.Call
}

// GetTitle is a helper method to define mock.On call
func (_e *EventMock_Expecter) GetTitle() *EventMock_GetTitle_Call {
	return &EventMock_GetTitle_Call{Call: _e.mock.On("GetTitle")}
}

func (_c *EventMock_GetTitle_Call) Run(run func()) *EventMock_GetTitle_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *EventMock_GetTitle_Call) Return(_a0 string) *EventMock_GetTitle_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *EventMock_GetTitle_Call) RunAndReturn(run func() string) *EventMock_GetTitle_Call {
	_c.Call.Return(run)
	return _c
}

// GetType provides a mock function with no fields
func (_m *EventMock) GetType() models.EventType {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetType")
	}

	var r0 models.EventType
	if rf, ok := ret.Get(0).(func() models.EventType); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(models.EventType)
	}

	return r0
}

// EventMock_GetType_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetType'
type EventMock_GetType_Call struct {
	*mock.Call
}

// GetType is a helper method to define mock.On call
func (_e *EventMock_Expecter) GetType() *EventMock_GetType_Call {
	return &EventMock_GetType_Call{Call: _e.mock.On("GetType")}
}

func (_c *EventMock_GetType_Call) Run(run func()) *EventMock_GetType_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *EventMock_GetType_Call) Return(_a0 models.EventType) *EventMock_GetType_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *EventMock_GetType_Call) RunAndReturn(run func() models.EventType) *EventMock_GetType_Call {
	_c.Call.Return(run)
	return _c
}

// GetUser provides a mock function with no fields
func (_m *EventMock) GetUser() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetUser")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// EventMock_GetUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUser'
type EventMock_GetUser_Call struct {
	*mock.Call
}

// GetUser is a helper method to define mock.On call
func (_e *EventMock_Expecter) GetUser() *EventMock_GetUser_Call {
	return &EventMock_GetUser_Call{Call: _e.mock.On("GetUser")}
}

func (_c *EventMock_GetUser_Call) Run(run func()) *EventMock_GetUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *EventMock_GetUser_Call) Return(_a0 string) *EventMock_GetUser_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *EventMock_GetUser_Call) RunAndReturn(run func() string) *EventMock_GetUser_Call {
	_c.Call.Return(run)
	return _c
}

// NewEventMock creates a new instance of EventMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewEventMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *EventMock {
	mock := &EventMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
