// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// FilterRepositoryMock is an autogenerated mock type for the FilterRepository type
type FilterRepositoryMock struct {
	mock.Mock
}

type FilterRepositoryMock_Expecter struct {
	mock *mock.Mock
}

func (_m *FilterRepositoryMock) EXPECT() *FilterRepositoryMock_Expecter {
	return &FilterRepositoryMock_Expecter{mock: &_m.Mock}
}

// AddFilterToLink provides a mock function with given fields: ctx, linkID, key, value
func (_m *FilterRepositoryMock) AddFilterToLink(ctx context.Context, linkID int64, key string, value string) error {
	ret := _m.Called(ctx, linkID, key, value)

	if len(ret) == 0 {
		panic("no return value specified for AddFilterToLink")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, string, string) error); ok {
		r0 = rf(ctx, linkID, key, value)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FilterRepositoryMock_AddFilterToLink_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddFilterToLink'
type FilterRepositoryMock_AddFilterToLink_Call struct {
	*mock.Call
}

// AddFilterToLink is a helper method to define mock.On call
//   - ctx context.Context
//   - linkID int64
//   - key string
//   - value string
func (_e *FilterRepositoryMock_Expecter) AddFilterToLink(ctx interface{}, linkID interface{}, key interface{}, value interface{}) *FilterRepositoryMock_AddFilterToLink_Call {
	return &FilterRepositoryMock_AddFilterToLink_Call{Call: _e.mock.On("AddFilterToLink", ctx, linkID, key, value)}
}

func (_c *FilterRepositoryMock_AddFilterToLink_Call) Run(run func(ctx context.Context, linkID int64, key string, value string)) *FilterRepositoryMock_AddFilterToLink_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *FilterRepositoryMock_AddFilterToLink_Call) Return(_a0 error) *FilterRepositoryMock_AddFilterToLink_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *FilterRepositoryMock_AddFilterToLink_Call) RunAndReturn(run func(context.Context, int64, string, string) error) *FilterRepositoryMock_AddFilterToLink_Call {
	_c.Call.Return(run)
	return _c
}

// GetFiltersByLink provides a mock function with given fields: ctx, linkID
func (_m *FilterRepositoryMock) GetFiltersByLink(ctx context.Context, linkID int64) ([]string, error) {
	ret := _m.Called(ctx, linkID)

	if len(ret) == 0 {
		panic("no return value specified for GetFiltersByLink")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) ([]string, error)); ok {
		return rf(ctx, linkID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) []string); ok {
		r0 = rf(ctx, linkID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, linkID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FilterRepositoryMock_GetFiltersByLink_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFiltersByLink'
type FilterRepositoryMock_GetFiltersByLink_Call struct {
	*mock.Call
}

// GetFiltersByLink is a helper method to define mock.On call
//   - ctx context.Context
//   - linkID int64
func (_e *FilterRepositoryMock_Expecter) GetFiltersByLink(ctx interface{}, linkID interface{}) *FilterRepositoryMock_GetFiltersByLink_Call {
	return &FilterRepositoryMock_GetFiltersByLink_Call{Call: _e.mock.On("GetFiltersByLink", ctx, linkID)}
}

func (_c *FilterRepositoryMock_GetFiltersByLink_Call) Run(run func(ctx context.Context, linkID int64)) *FilterRepositoryMock_GetFiltersByLink_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *FilterRepositoryMock_GetFiltersByLink_Call) Return(_a0 []string, _a1 error) *FilterRepositoryMock_GetFiltersByLink_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *FilterRepositoryMock_GetFiltersByLink_Call) RunAndReturn(run func(context.Context, int64) ([]string, error)) *FilterRepositoryMock_GetFiltersByLink_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveFiltersFromLink provides a mock function with given fields: ctx, linkID
func (_m *FilterRepositoryMock) RemoveFiltersFromLink(ctx context.Context, linkID int64) error {
	ret := _m.Called(ctx, linkID)

	if len(ret) == 0 {
		panic("no return value specified for RemoveFiltersFromLink")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = rf(ctx, linkID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FilterRepositoryMock_RemoveFiltersFromLink_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveFiltersFromLink'
type FilterRepositoryMock_RemoveFiltersFromLink_Call struct {
	*mock.Call
}

// RemoveFiltersFromLink is a helper method to define mock.On call
//   - ctx context.Context
//   - linkID int64
func (_e *FilterRepositoryMock_Expecter) RemoveFiltersFromLink(ctx interface{}, linkID interface{}) *FilterRepositoryMock_RemoveFiltersFromLink_Call {
	return &FilterRepositoryMock_RemoveFiltersFromLink_Call{Call: _e.mock.On("RemoveFiltersFromLink", ctx, linkID)}
}

func (_c *FilterRepositoryMock_RemoveFiltersFromLink_Call) Run(run func(ctx context.Context, linkID int64)) *FilterRepositoryMock_RemoveFiltersFromLink_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *FilterRepositoryMock_RemoveFiltersFromLink_Call) Return(_a0 error) *FilterRepositoryMock_RemoveFiltersFromLink_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *FilterRepositoryMock_RemoveFiltersFromLink_Call) RunAndReturn(run func(context.Context, int64) error) *FilterRepositoryMock_RemoveFiltersFromLink_Call {
	_c.Call.Return(run)
	return _c
}

// NewFilterRepositoryMock creates a new instance of FilterRepositoryMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewFilterRepositoryMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *FilterRepositoryMock {
	mock := &FilterRepositoryMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
