// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	models "github.com/es-debug/backend-academy-2024-go-template/internal/domain/models"
	mock "github.com/stretchr/testify/mock"
)

// LinkRepositoryMock is an autogenerated mock type for the LinkRepository type
type LinkRepositoryMock struct {
	mock.Mock
}

type LinkRepositoryMock_Expecter struct {
	mock *mock.Mock
}

func (_m *LinkRepositoryMock) EXPECT() *LinkRepositoryMock_Expecter {
	return &LinkRepositoryMock_Expecter{mock: &_m.Mock}
}

// AddLink provides a mock function with given fields: ctx, link
func (_m *LinkRepositoryMock) AddLink(ctx context.Context, link *models.Link) (*int64, error) {
	ret := _m.Called(ctx, link)

	if len(ret) == 0 {
		panic("no return value specified for AddLink")
	}

	var r0 *int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.Link) (*int64, error)); ok {
		return rf(ctx, link)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *models.Link) *int64); ok {
		r0 = rf(ctx, link)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*int64)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *models.Link) error); ok {
		r1 = rf(ctx, link)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// LinkRepositoryMock_AddLink_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddLink'
type LinkRepositoryMock_AddLink_Call struct {
	*mock.Call
}

// AddLink is a helper method to define mock.On call
//   - ctx context.Context
//   - link *models.Link
func (_e *LinkRepositoryMock_Expecter) AddLink(ctx interface{}, link interface{}) *LinkRepositoryMock_AddLink_Call {
	return &LinkRepositoryMock_AddLink_Call{Call: _e.mock.On("AddLink", ctx, link)}
}

func (_c *LinkRepositoryMock_AddLink_Call) Run(run func(ctx context.Context, link *models.Link)) *LinkRepositoryMock_AddLink_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.Link))
	})
	return _c
}

func (_c *LinkRepositoryMock_AddLink_Call) Return(_a0 *int64, _a1 error) *LinkRepositoryMock_AddLink_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *LinkRepositoryMock_AddLink_Call) RunAndReturn(run func(context.Context, *models.Link) (*int64, error)) *LinkRepositoryMock_AddLink_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteLink provides a mock function with given fields: ctx, chatID, url
func (_m *LinkRepositoryMock) DeleteLink(ctx context.Context, chatID int64, url string) (*models.Link, error) {
	ret := _m.Called(ctx, chatID, url)

	if len(ret) == 0 {
		panic("no return value specified for DeleteLink")
	}

	var r0 *models.Link
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, string) (*models.Link, error)); ok {
		return rf(ctx, chatID, url)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, string) *models.Link); ok {
		r0 = rf(ctx, chatID, url)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Link)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, string) error); ok {
		r1 = rf(ctx, chatID, url)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// LinkRepositoryMock_DeleteLink_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteLink'
type LinkRepositoryMock_DeleteLink_Call struct {
	*mock.Call
}

// DeleteLink is a helper method to define mock.On call
//   - ctx context.Context
//   - chatID int64
//   - url string
func (_e *LinkRepositoryMock_Expecter) DeleteLink(ctx interface{}, chatID interface{}, url interface{}) *LinkRepositoryMock_DeleteLink_Call {
	return &LinkRepositoryMock_DeleteLink_Call{Call: _e.mock.On("DeleteLink", ctx, chatID, url)}
}

func (_c *LinkRepositoryMock_DeleteLink_Call) Run(run func(ctx context.Context, chatID int64, url string)) *LinkRepositoryMock_DeleteLink_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(string))
	})
	return _c
}

func (_c *LinkRepositoryMock_DeleteLink_Call) Return(_a0 *models.Link, _a1 error) *LinkRepositoryMock_DeleteLink_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *LinkRepositoryMock_DeleteLink_Call) RunAndReturn(run func(context.Context, int64, string) (*models.Link, error)) *LinkRepositoryMock_DeleteLink_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllActiveLinks provides a mock function with given fields: ctx
func (_m *LinkRepositoryMock) GetAllActiveLinks(ctx context.Context) ([]models.Link, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAllActiveLinks")
	}

	var r0 []models.Link
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]models.Link, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []models.Link); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Link)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// LinkRepositoryMock_GetAllActiveLinks_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllActiveLinks'
type LinkRepositoryMock_GetAllActiveLinks_Call struct {
	*mock.Call
}

// GetAllActiveLinks is a helper method to define mock.On call
//   - ctx context.Context
func (_e *LinkRepositoryMock_Expecter) GetAllActiveLinks(ctx interface{}) *LinkRepositoryMock_GetAllActiveLinks_Call {
	return &LinkRepositoryMock_GetAllActiveLinks_Call{Call: _e.mock.On("GetAllActiveLinks", ctx)}
}

func (_c *LinkRepositoryMock_GetAllActiveLinks_Call) Run(run func(ctx context.Context)) *LinkRepositoryMock_GetAllActiveLinks_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *LinkRepositoryMock_GetAllActiveLinks_Call) Return(_a0 []models.Link, _a1 error) *LinkRepositoryMock_GetAllActiveLinks_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *LinkRepositoryMock_GetAllActiveLinks_Call) RunAndReturn(run func(context.Context) ([]models.Link, error)) *LinkRepositoryMock_GetAllActiveLinks_Call {
	_c.Call.Return(run)
	return _c
}

// GetLinkByURL provides a mock function with given fields: ctx, chatID, url
func (_m *LinkRepositoryMock) GetLinkByURL(ctx context.Context, chatID int64, url string) (*models.Link, error) {
	ret := _m.Called(ctx, chatID, url)

	if len(ret) == 0 {
		panic("no return value specified for GetLinkByURL")
	}

	var r0 *models.Link
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, string) (*models.Link, error)); ok {
		return rf(ctx, chatID, url)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, string) *models.Link); ok {
		r0 = rf(ctx, chatID, url)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Link)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, string) error); ok {
		r1 = rf(ctx, chatID, url)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// LinkRepositoryMock_GetLinkByURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLinkByURL'
type LinkRepositoryMock_GetLinkByURL_Call struct {
	*mock.Call
}

// GetLinkByURL is a helper method to define mock.On call
//   - ctx context.Context
//   - chatID int64
//   - url string
func (_e *LinkRepositoryMock_Expecter) GetLinkByURL(ctx interface{}, chatID interface{}, url interface{}) *LinkRepositoryMock_GetLinkByURL_Call {
	return &LinkRepositoryMock_GetLinkByURL_Call{Call: _e.mock.On("GetLinkByURL", ctx, chatID, url)}
}

func (_c *LinkRepositoryMock_GetLinkByURL_Call) Run(run func(ctx context.Context, chatID int64, url string)) *LinkRepositoryMock_GetLinkByURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(string))
	})
	return _c
}

func (_c *LinkRepositoryMock_GetLinkByURL_Call) Return(_a0 *models.Link, _a1 error) *LinkRepositoryMock_GetLinkByURL_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *LinkRepositoryMock_GetLinkByURL_Call) RunAndReturn(run func(context.Context, int64, string) (*models.Link, error)) *LinkRepositoryMock_GetLinkByURL_Call {
	_c.Call.Return(run)
	return _c
}

// GetLinksByUser provides a mock function with given fields: ctx, chatID
func (_m *LinkRepositoryMock) GetLinksByUser(ctx context.Context, chatID int64) ([]models.Link, error) {
	ret := _m.Called(ctx, chatID)

	if len(ret) == 0 {
		panic("no return value specified for GetLinksByUser")
	}

	var r0 []models.Link
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) ([]models.Link, error)); ok {
		return rf(ctx, chatID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) []models.Link); ok {
		r0 = rf(ctx, chatID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Link)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, chatID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// LinkRepositoryMock_GetLinksByUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLinksByUser'
type LinkRepositoryMock_GetLinksByUser_Call struct {
	*mock.Call
}

// GetLinksByUser is a helper method to define mock.On call
//   - ctx context.Context
//   - chatID int64
func (_e *LinkRepositoryMock_Expecter) GetLinksByUser(ctx interface{}, chatID interface{}) *LinkRepositoryMock_GetLinksByUser_Call {
	return &LinkRepositoryMock_GetLinksByUser_Call{Call: _e.mock.On("GetLinksByUser", ctx, chatID)}
}

func (_c *LinkRepositoryMock_GetLinksByUser_Call) Run(run func(ctx context.Context, chatID int64)) *LinkRepositoryMock_GetLinksByUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *LinkRepositoryMock_GetLinksByUser_Call) Return(_a0 []models.Link, _a1 error) *LinkRepositoryMock_GetLinksByUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *LinkRepositoryMock_GetLinksByUser_Call) RunAndReturn(run func(context.Context, int64) ([]models.Link, error)) *LinkRepositoryMock_GetLinksByUser_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateLink provides a mock function with given fields: ctx, link
func (_m *LinkRepositoryMock) UpdateLink(ctx context.Context, link *models.Link) error {
	ret := _m.Called(ctx, link)

	if len(ret) == 0 {
		panic("no return value specified for UpdateLink")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.Link) error); ok {
		r0 = rf(ctx, link)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// LinkRepositoryMock_UpdateLink_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateLink'
type LinkRepositoryMock_UpdateLink_Call struct {
	*mock.Call
}

// UpdateLink is a helper method to define mock.On call
//   - ctx context.Context
//   - link *models.Link
func (_e *LinkRepositoryMock_Expecter) UpdateLink(ctx interface{}, link interface{}) *LinkRepositoryMock_UpdateLink_Call {
	return &LinkRepositoryMock_UpdateLink_Call{Call: _e.mock.On("UpdateLink", ctx, link)}
}

func (_c *LinkRepositoryMock_UpdateLink_Call) Run(run func(ctx context.Context, link *models.Link)) *LinkRepositoryMock_UpdateLink_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.Link))
	})
	return _c
}

func (_c *LinkRepositoryMock_UpdateLink_Call) Return(_a0 error) *LinkRepositoryMock_UpdateLink_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *LinkRepositoryMock_UpdateLink_Call) RunAndReturn(run func(context.Context, *models.Link) error) *LinkRepositoryMock_UpdateLink_Call {
	_c.Call.Return(run)
	return _c
}

// NewLinkRepositoryMock creates a new instance of LinkRepositoryMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewLinkRepositoryMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *LinkRepositoryMock {
	mock := &LinkRepositoryMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
