// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	models "github.com/es-debug/backend-academy-2024-go-template/internal/domain/models"
	mock "github.com/stretchr/testify/mock"
)

// LinkCheckerMock is an autogenerated mock type for the LinkChecker type
type LinkCheckerMock struct {
	mock.Mock
}

type LinkCheckerMock_Expecter struct {
	mock *mock.Mock
}

func (_m *LinkCheckerMock) EXPECT() *LinkCheckerMock_Expecter {
	return &LinkCheckerMock_Expecter{mock: &_m.Mock}
}

// GetEvent provides a mock function with given fields: url
func (_m *LinkCheckerMock) GetEvent(url string) (models.Event, error) {
	ret := _m.Called(url)

	if len(ret) == 0 {
		panic("no return value specified for GetEvent")
	}

	var r0 models.Event
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (models.Event, error)); ok {
		return rf(url)
	}
	if rf, ok := ret.Get(0).(func(string) models.Event); ok {
		r0 = rf(url)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(models.Event)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(url)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// LinkCheckerMock_GetEvent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetEvent'
type LinkCheckerMock_GetEvent_Call struct {
	*mock.Call
}

// GetEvent is a helper method to define mock.On call
//   - url string
func (_e *LinkCheckerMock_Expecter) GetEvent(url interface{}) *LinkCheckerMock_GetEvent_Call {
	return &LinkCheckerMock_GetEvent_Call{Call: _e.mock.On("GetEvent", url)}
}

func (_c *LinkCheckerMock_GetEvent_Call) Run(run func(url string)) *LinkCheckerMock_GetEvent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *LinkCheckerMock_GetEvent_Call) Return(_a0 models.Event, _a1 error) *LinkCheckerMock_GetEvent_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *LinkCheckerMock_GetEvent_Call) RunAndReturn(run func(string) (models.Event, error)) *LinkCheckerMock_GetEvent_Call {
	_c.Call.Return(run)
	return _c
}

// NewLinkCheckerMock creates a new instance of LinkCheckerMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewLinkCheckerMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *LinkCheckerMock {
	mock := &LinkCheckerMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
