// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	time "time"

	models "github.com/es-debug/backend-academy-2024-go-template/internal/domain/models"
	mock "github.com/stretchr/testify/mock"
)

// LinkCheckerMock is an autogenerated mock type for the LinkChecker type
type LinkCheckerMock struct {
	mock.Mock
}

type LinkCheckerMock_Expecter struct {
	mock *mock.Mock
}

func (_m *LinkCheckerMock) EXPECT() *LinkCheckerMock_Expecter {
	return &LinkCheckerMock_Expecter{mock: &_m.Mock}
}

// GetQuestionTitle provides a mock function with given fields: url
func (_m *LinkCheckerMock) GetQuestionTitle(url string) (string, error) {
	ret := _m.Called(url)

	if len(ret) == 0 {
		panic("no return value specified for GetQuestionTitle")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (string, error)); ok {
		return rf(url)
	}
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(url)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(url)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// LinkCheckerMock_GetQuestionTitle_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetQuestionTitle'
type LinkCheckerMock_GetQuestionTitle_Call struct {
	*mock.Call
}

// GetQuestionTitle is a helper method to define mock.On call
//   - url string
func (_e *LinkCheckerMock_Expecter) GetQuestionTitle(url interface{}) *LinkCheckerMock_GetQuestionTitle_Call {
	return &LinkCheckerMock_GetQuestionTitle_Call{Call: _e.mock.On("GetQuestionTitle", url)}
}

func (_c *LinkCheckerMock_GetQuestionTitle_Call) Run(run func(url string)) *LinkCheckerMock_GetQuestionTitle_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *LinkCheckerMock_GetQuestionTitle_Call) Return(_a0 string, _a1 error) *LinkCheckerMock_GetQuestionTitle_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *LinkCheckerMock_GetQuestionTitle_Call) RunAndReturn(run func(string) (string, error)) *LinkCheckerMock_GetQuestionTitle_Call {
	_c.Call.Return(run)
	return _c
}

// GetUpdates provides a mock function with given fields: url, since
func (_m *LinkCheckerMock) GetUpdates(url string, since time.Time) ([]models.Event, error) {
	ret := _m.Called(url, since)

	if len(ret) == 0 {
		panic("no return value specified for GetUpdates")
	}

	var r0 []models.Event
	var r1 error
	if rf, ok := ret.Get(0).(func(string, time.Time) ([]models.Event, error)); ok {
		return rf(url, since)
	}
	if rf, ok := ret.Get(0).(func(string, time.Time) []models.Event); ok {
		r0 = rf(url, since)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Event)
		}
	}

	if rf, ok := ret.Get(1).(func(string, time.Time) error); ok {
		r1 = rf(url, since)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// LinkCheckerMock_GetUpdates_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUpdates'
type LinkCheckerMock_GetUpdates_Call struct {
	*mock.Call
}

// GetUpdates is a helper method to define mock.On call
//   - url string
//   - since time.Time
func (_e *LinkCheckerMock_Expecter) GetUpdates(url interface{}, since interface{}) *LinkCheckerMock_GetUpdates_Call {
	return &LinkCheckerMock_GetUpdates_Call{Call: _e.mock.On("GetUpdates", url, since)}
}

func (_c *LinkCheckerMock_GetUpdates_Call) Run(run func(url string, since time.Time)) *LinkCheckerMock_GetUpdates_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(time.Time))
	})
	return _c
}

func (_c *LinkCheckerMock_GetUpdates_Call) Return(_a0 []models.Event, _a1 error) *LinkCheckerMock_GetUpdates_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *LinkCheckerMock_GetUpdates_Call) RunAndReturn(run func(string, time.Time) ([]models.Event, error)) *LinkCheckerMock_GetUpdates_Call {
	_c.Call.Return(run)
	return _c
}

// NewLinkCheckerMock creates a new instance of LinkCheckerMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewLinkCheckerMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *LinkCheckerMock {
	mock := &LinkCheckerMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
