// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	scrapper_api "github.com/es-debug/backend-academy-2024-go-template/internal/api/openapi/v1/servers/scrapper"
	models "github.com/es-debug/backend-academy-2024-go-template/internal/domain/models"
	mock "github.com/stretchr/testify/mock"

	service "github.com/es-debug/backend-academy-2024-go-template/internal/application/service"
)

// LinksServiceMock is an autogenerated mock type for the LinksService type
type LinksServiceMock struct {
	mock.Mock
}

type LinksServiceMock_Expecter struct {
	mock *mock.Mock
}

func (_m *LinksServiceMock) EXPECT() *LinksServiceMock_Expecter {
	return &LinksServiceMock_Expecter{mock: &_m.Mock}
}

// DeleteLink provides a mock function with given fields: ctx, chatID, url
func (_m *LinksServiceMock) DeleteLink(ctx context.Context, chatID int64, url string) (*models.Link, *service.LinkMeta, error) {
	ret := _m.Called(ctx, chatID, url)

	if len(ret) == 0 {
		panic("no return value specified for DeleteLink")
	}

	var r0 *models.Link
	var r1 *service.LinkMeta
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, string) (*models.Link, *service.LinkMeta, error)); ok {
		return rf(ctx, chatID, url)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, string) *models.Link); ok {
		r0 = rf(ctx, chatID, url)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Link)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, string) *service.LinkMeta); ok {
		r1 = rf(ctx, chatID, url)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*service.LinkMeta)
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context, int64, string) error); ok {
		r2 = rf(ctx, chatID, url)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// LinksServiceMock_DeleteLink_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteLink'
type LinksServiceMock_DeleteLink_Call struct {
	*mock.Call
}

// DeleteLink is a helper method to define mock.On call
//   - ctx context.Context
//   - chatID int64
//   - url string
func (_e *LinksServiceMock_Expecter) DeleteLink(ctx interface{}, chatID interface{}, url interface{}) *LinksServiceMock_DeleteLink_Call {
	return &LinksServiceMock_DeleteLink_Call{Call: _e.mock.On("DeleteLink", ctx, chatID, url)}
}

func (_c *LinksServiceMock_DeleteLink_Call) Run(run func(ctx context.Context, chatID int64, url string)) *LinksServiceMock_DeleteLink_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(string))
	})
	return _c
}

func (_c *LinksServiceMock_DeleteLink_Call) Return(link *models.Link, meta *service.LinkMeta, err error) *LinksServiceMock_DeleteLink_Call {
	_c.Call.Return(link, meta, err)
	return _c
}

func (_c *LinksServiceMock_DeleteLink_Call) RunAndReturn(run func(context.Context, int64, string) (*models.Link, *service.LinkMeta, error)) *LinksServiceMock_DeleteLink_Call {
	_c.Call.Return(run)
	return _c
}

// RetrieveLinks provides a mock function with given fields: ctx, chatID
func (_m *LinksServiceMock) RetrieveLinks(ctx context.Context, chatID int64) ([]scrapper_api.LinkResponse, error) {
	ret := _m.Called(ctx, chatID)

	if len(ret) == 0 {
		panic("no return value specified for RetrieveLinks")
	}

	var r0 []scrapper_api.LinkResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) ([]scrapper_api.LinkResponse, error)); ok {
		return rf(ctx, chatID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) []scrapper_api.LinkResponse); ok {
		r0 = rf(ctx, chatID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]scrapper_api.LinkResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, chatID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// LinksServiceMock_RetrieveLinks_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RetrieveLinks'
type LinksServiceMock_RetrieveLinks_Call struct {
	*mock.Call
}

// RetrieveLinks is a helper method to define mock.On call
//   - ctx context.Context
//   - chatID int64
func (_e *LinksServiceMock_Expecter) RetrieveLinks(ctx interface{}, chatID interface{}) *LinksServiceMock_RetrieveLinks_Call {
	return &LinksServiceMock_RetrieveLinks_Call{Call: _e.mock.On("RetrieveLinks", ctx, chatID)}
}

func (_c *LinksServiceMock_RetrieveLinks_Call) Run(run func(ctx context.Context, chatID int64)) *LinksServiceMock_RetrieveLinks_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *LinksServiceMock_RetrieveLinks_Call) Return(links []scrapper_api.LinkResponse, err error) *LinksServiceMock_RetrieveLinks_Call {
	_c.Call.Return(links, err)
	return _c
}

func (_c *LinksServiceMock_RetrieveLinks_Call) RunAndReturn(run func(context.Context, int64) ([]scrapper_api.LinkResponse, error)) *LinksServiceMock_RetrieveLinks_Call {
	_c.Call.Return(run)
	return _c
}

// RetrieveMeta provides a mock function with given fields: ctx, chatID, url
func (_m *LinksServiceMock) RetrieveMeta(ctx context.Context, chatID int64, url string) (*service.LinkMeta, error) {
	ret := _m.Called(ctx, chatID, url)

	if len(ret) == 0 {
		panic("no return value specified for RetrieveMeta")
	}

	var r0 *service.LinkMeta
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, string) (*service.LinkMeta, error)); ok {
		return rf(ctx, chatID, url)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, string) *service.LinkMeta); ok {
		r0 = rf(ctx, chatID, url)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*service.LinkMeta)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, string) error); ok {
		r1 = rf(ctx, chatID, url)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// LinksServiceMock_RetrieveMeta_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RetrieveMeta'
type LinksServiceMock_RetrieveMeta_Call struct {
	*mock.Call
}

// RetrieveMeta is a helper method to define mock.On call
//   - ctx context.Context
//   - chatID int64
//   - url string
func (_e *LinksServiceMock_Expecter) RetrieveMeta(ctx interface{}, chatID interface{}, url interface{}) *LinksServiceMock_RetrieveMeta_Call {
	return &LinksServiceMock_RetrieveMeta_Call{Call: _e.mock.On("RetrieveMeta", ctx, chatID, url)}
}

func (_c *LinksServiceMock_RetrieveMeta_Call) Run(run func(ctx context.Context, chatID int64, url string)) *LinksServiceMock_RetrieveMeta_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(string))
	})
	return _c
}

func (_c *LinksServiceMock_RetrieveMeta_Call) Return(meta *service.LinkMeta, err error) *LinksServiceMock_RetrieveMeta_Call {
	_c.Call.Return(meta, err)
	return _c
}

func (_c *LinksServiceMock_RetrieveMeta_Call) RunAndReturn(run func(context.Context, int64, string) (*service.LinkMeta, error)) *LinksServiceMock_RetrieveMeta_Call {
	_c.Call.Return(run)
	return _c
}

// TrackLink provides a mock function with given fields: ctx, chatID, url, tags, filters
func (_m *LinksServiceMock) TrackLink(ctx context.Context, chatID int64, url string, tags []string, filters []string) (*models.Link, error) {
	ret := _m.Called(ctx, chatID, url, tags, filters)

	if len(ret) == 0 {
		panic("no return value specified for TrackLink")
	}

	var r0 *models.Link
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, string, []string, []string) (*models.Link, error)); ok {
		return rf(ctx, chatID, url, tags, filters)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, string, []string, []string) *models.Link); ok {
		r0 = rf(ctx, chatID, url, tags, filters)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Link)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, string, []string, []string) error); ok {
		r1 = rf(ctx, chatID, url, tags, filters)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// LinksServiceMock_TrackLink_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TrackLink'
type LinksServiceMock_TrackLink_Call struct {
	*mock.Call
}

// TrackLink is a helper method to define mock.On call
//   - ctx context.Context
//   - chatID int64
//   - url string
//   - tags []string
//   - filters []string
func (_e *LinksServiceMock_Expecter) TrackLink(ctx interface{}, chatID interface{}, url interface{}, tags interface{}, filters interface{}) *LinksServiceMock_TrackLink_Call {
	return &LinksServiceMock_TrackLink_Call{Call: _e.mock.On("TrackLink", ctx, chatID, url, tags, filters)}
}

func (_c *LinksServiceMock_TrackLink_Call) Run(run func(ctx context.Context, chatID int64, url string, tags []string, filters []string)) *LinksServiceMock_TrackLink_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(string), args[3].([]string), args[4].([]string))
	})
	return _c
}

func (_c *LinksServiceMock_TrackLink_Call) Return(link *models.Link, err error) *LinksServiceMock_TrackLink_Call {
	_c.Call.Return(link, err)
	return _c
}

func (_c *LinksServiceMock_TrackLink_Call) RunAndReturn(run func(context.Context, int64, string, []string, []string) (*models.Link, error)) *LinksServiceMock_TrackLink_Call {
	_c.Call.Return(run)
	return _c
}

// NewLinksServiceMock creates a new instance of LinksServiceMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewLinksServiceMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *LinksServiceMock {
	mock := &LinksServiceMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
