// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// TagRepositoryMock is an autogenerated mock type for the TagRepository type
type TagRepositoryMock struct {
	mock.Mock
}

type TagRepositoryMock_Expecter struct {
	mock *mock.Mock
}

func (_m *TagRepositoryMock) EXPECT() *TagRepositoryMock_Expecter {
	return &TagRepositoryMock_Expecter{mock: &_m.Mock}
}

// AddTagToLink provides a mock function with given fields: ctx, chatID, linkURL, tagName
func (_m *TagRepositoryMock) AddTagToLink(ctx context.Context, chatID int64, linkURL string, tagName string) error {
	ret := _m.Called(ctx, chatID, linkURL, tagName)

	if len(ret) == 0 {
		panic("no return value specified for AddTagToLink")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, string, string) error); ok {
		r0 = rf(ctx, chatID, linkURL, tagName)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// TagRepositoryMock_AddTagToLink_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddTagToLink'
type TagRepositoryMock_AddTagToLink_Call struct {
	*mock.Call
}

// AddTagToLink is a helper method to define mock.On call
//   - ctx context.Context
//   - chatID int64
//   - linkURL string
//   - tagName string
func (_e *TagRepositoryMock_Expecter) AddTagToLink(ctx interface{}, chatID interface{}, linkURL interface{}, tagName interface{}) *TagRepositoryMock_AddTagToLink_Call {
	return &TagRepositoryMock_AddTagToLink_Call{Call: _e.mock.On("AddTagToLink", ctx, chatID, linkURL, tagName)}
}

func (_c *TagRepositoryMock_AddTagToLink_Call) Run(run func(ctx context.Context, chatID int64, linkURL string, tagName string)) *TagRepositoryMock_AddTagToLink_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *TagRepositoryMock_AddTagToLink_Call) Return(_a0 error) *TagRepositoryMock_AddTagToLink_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *TagRepositoryMock_AddTagToLink_Call) RunAndReturn(run func(context.Context, int64, string, string) error) *TagRepositoryMock_AddTagToLink_Call {
	_c.Call.Return(run)
	return _c
}

// AddTagToUser provides a mock function with given fields: ctx, userID, tagName
func (_m *TagRepositoryMock) AddTagToUser(ctx context.Context, userID int64, tagName string) (*int64, error) {
	ret := _m.Called(ctx, userID, tagName)

	if len(ret) == 0 {
		panic("no return value specified for AddTagToUser")
	}

	var r0 *int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, string) (*int64, error)); ok {
		return rf(ctx, userID, tagName)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, string) *int64); ok {
		r0 = rf(ctx, userID, tagName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*int64)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, string) error); ok {
		r1 = rf(ctx, userID, tagName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TagRepositoryMock_AddTagToUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddTagToUser'
type TagRepositoryMock_AddTagToUser_Call struct {
	*mock.Call
}

// AddTagToUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
//   - tagName string
func (_e *TagRepositoryMock_Expecter) AddTagToUser(ctx interface{}, userID interface{}, tagName interface{}) *TagRepositoryMock_AddTagToUser_Call {
	return &TagRepositoryMock_AddTagToUser_Call{Call: _e.mock.On("AddTagToUser", ctx, userID, tagName)}
}

func (_c *TagRepositoryMock_AddTagToUser_Call) Run(run func(ctx context.Context, userID int64, tagName string)) *TagRepositoryMock_AddTagToUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(string))
	})
	return _c
}

func (_c *TagRepositoryMock_AddTagToUser_Call) Return(_a0 *int64, _a1 error) *TagRepositoryMock_AddTagToUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TagRepositoryMock_AddTagToUser_Call) RunAndReturn(run func(context.Context, int64, string) (*int64, error)) *TagRepositoryMock_AddTagToUser_Call {
	_c.Call.Return(run)
	return _c
}

// GetTagsByLink provides a mock function with given fields: ctx, linkID
func (_m *TagRepositoryMock) GetTagsByLink(ctx context.Context, linkID int64) ([]string, error) {
	ret := _m.Called(ctx, linkID)

	if len(ret) == 0 {
		panic("no return value specified for GetTagsByLink")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) ([]string, error)); ok {
		return rf(ctx, linkID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) []string); ok {
		r0 = rf(ctx, linkID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, linkID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TagRepositoryMock_GetTagsByLink_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTagsByLink'
type TagRepositoryMock_GetTagsByLink_Call struct {
	*mock.Call
}

// GetTagsByLink is a helper method to define mock.On call
//   - ctx context.Context
//   - linkID int64
func (_e *TagRepositoryMock_Expecter) GetTagsByLink(ctx interface{}, linkID interface{}) *TagRepositoryMock_GetTagsByLink_Call {
	return &TagRepositoryMock_GetTagsByLink_Call{Call: _e.mock.On("GetTagsByLink", ctx, linkID)}
}

func (_c *TagRepositoryMock_GetTagsByLink_Call) Run(run func(ctx context.Context, linkID int64)) *TagRepositoryMock_GetTagsByLink_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *TagRepositoryMock_GetTagsByLink_Call) Return(_a0 []string, _a1 error) *TagRepositoryMock_GetTagsByLink_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TagRepositoryMock_GetTagsByLink_Call) RunAndReturn(run func(context.Context, int64) ([]string, error)) *TagRepositoryMock_GetTagsByLink_Call {
	_c.Call.Return(run)
	return _c
}

// GetTagsByUser provides a mock function with given fields: ctx, chatID
func (_m *TagRepositoryMock) GetTagsByUser(ctx context.Context, chatID int64) ([]string, error) {
	ret := _m.Called(ctx, chatID)

	if len(ret) == 0 {
		panic("no return value specified for GetTagsByUser")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) ([]string, error)); ok {
		return rf(ctx, chatID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) []string); ok {
		r0 = rf(ctx, chatID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, chatID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TagRepositoryMock_GetTagsByUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTagsByUser'
type TagRepositoryMock_GetTagsByUser_Call struct {
	*mock.Call
}

// GetTagsByUser is a helper method to define mock.On call
//   - ctx context.Context
//   - chatID int64
func (_e *TagRepositoryMock_Expecter) GetTagsByUser(ctx interface{}, chatID interface{}) *TagRepositoryMock_GetTagsByUser_Call {
	return &TagRepositoryMock_GetTagsByUser_Call{Call: _e.mock.On("GetTagsByUser", ctx, chatID)}
}

func (_c *TagRepositoryMock_GetTagsByUser_Call) Run(run func(ctx context.Context, chatID int64)) *TagRepositoryMock_GetTagsByUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *TagRepositoryMock_GetTagsByUser_Call) Return(_a0 []string, _a1 error) *TagRepositoryMock_GetTagsByUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TagRepositoryMock_GetTagsByUser_Call) RunAndReturn(run func(context.Context, int64) ([]string, error)) *TagRepositoryMock_GetTagsByUser_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveTagsFromLink provides a mock function with given fields: ctx, linkID
func (_m *TagRepositoryMock) RemoveTagsFromLink(ctx context.Context, linkID int64) error {
	ret := _m.Called(ctx, linkID)

	if len(ret) == 0 {
		panic("no return value specified for RemoveTagsFromLink")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = rf(ctx, linkID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// TagRepositoryMock_RemoveTagsFromLink_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveTagsFromLink'
type TagRepositoryMock_RemoveTagsFromLink_Call struct {
	*mock.Call
}

// RemoveTagsFromLink is a helper method to define mock.On call
//   - ctx context.Context
//   - linkID int64
func (_e *TagRepositoryMock_Expecter) RemoveTagsFromLink(ctx interface{}, linkID interface{}) *TagRepositoryMock_RemoveTagsFromLink_Call {
	return &TagRepositoryMock_RemoveTagsFromLink_Call{Call: _e.mock.On("RemoveTagsFromLink", ctx, linkID)}
}

func (_c *TagRepositoryMock_RemoveTagsFromLink_Call) Run(run func(ctx context.Context, linkID int64)) *TagRepositoryMock_RemoveTagsFromLink_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *TagRepositoryMock_RemoveTagsFromLink_Call) Return(_a0 error) *TagRepositoryMock_RemoveTagsFromLink_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *TagRepositoryMock_RemoveTagsFromLink_Call) RunAndReturn(run func(context.Context, int64) error) *TagRepositoryMock_RemoveTagsFromLink_Call {
	_c.Call.Return(run)
	return _c
}

// NewTagRepositoryMock creates a new instance of TagRepositoryMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTagRepositoryMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *TagRepositoryMock {
	mock := &TagRepositoryMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
