// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	models "github.com/es-debug/backend-academy-2024-go-template/internal/domain/models"
	mock "github.com/stretchr/testify/mock"
)

// UserRepositoryMock is an autogenerated mock type for the UserRepository type
type UserRepositoryMock struct {
	mock.Mock
}

type UserRepositoryMock_Expecter struct {
	mock *mock.Mock
}

func (_m *UserRepositoryMock) EXPECT() *UserRepositoryMock_Expecter {
	return &UserRepositoryMock_Expecter{mock: &_m.Mock}
}

// AddUser provides a mock function with given fields: ctx, user
func (_m *UserRepositoryMock) AddUser(ctx context.Context, user *models.User) error {
	ret := _m.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for AddUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.User) error); ok {
		r0 = rf(ctx, user)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UserRepositoryMock_AddUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddUser'
type UserRepositoryMock_AddUser_Call struct {
	*mock.Call
}

// AddUser is a helper method to define mock.On call
//   - ctx context.Context
//   - user *models.User
func (_e *UserRepositoryMock_Expecter) AddUser(ctx interface{}, user interface{}) *UserRepositoryMock_AddUser_Call {
	return &UserRepositoryMock_AddUser_Call{Call: _e.mock.On("AddUser", ctx, user)}
}

func (_c *UserRepositoryMock_AddUser_Call) Run(run func(ctx context.Context, user *models.User)) *UserRepositoryMock_AddUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.User))
	})
	return _c
}

func (_c *UserRepositoryMock_AddUser_Call) Return(_a0 error) *UserRepositoryMock_AddUser_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *UserRepositoryMock_AddUser_Call) RunAndReturn(run func(context.Context, *models.User) error) *UserRepositoryMock_AddUser_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteUser provides a mock function with given fields: ctx, chatID
func (_m *UserRepositoryMock) DeleteUser(ctx context.Context, chatID int64) error {
	ret := _m.Called(ctx, chatID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = rf(ctx, chatID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UserRepositoryMock_DeleteUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteUser'
type UserRepositoryMock_DeleteUser_Call struct {
	*mock.Call
}

// DeleteUser is a helper method to define mock.On call
//   - ctx context.Context
//   - chatID int64
func (_e *UserRepositoryMock_Expecter) DeleteUser(ctx interface{}, chatID interface{}) *UserRepositoryMock_DeleteUser_Call {
	return &UserRepositoryMock_DeleteUser_Call{Call: _e.mock.On("DeleteUser", ctx, chatID)}
}

func (_c *UserRepositoryMock_DeleteUser_Call) Run(run func(ctx context.Context, chatID int64)) *UserRepositoryMock_DeleteUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *UserRepositoryMock_DeleteUser_Call) Return(_a0 error) *UserRepositoryMock_DeleteUser_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *UserRepositoryMock_DeleteUser_Call) RunAndReturn(run func(context.Context, int64) error) *UserRepositoryMock_DeleteUser_Call {
	_c.Call.Return(run)
	return _c
}

// GetUser provides a mock function with given fields: ctx, chatID
func (_m *UserRepositoryMock) GetUser(ctx context.Context, chatID int64) (*models.User, error) {
	ret := _m.Called(ctx, chatID)

	if len(ret) == 0 {
		panic("no return value specified for GetUser")
	}

	var r0 *models.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (*models.User, error)); ok {
		return rf(ctx, chatID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) *models.User); ok {
		r0 = rf(ctx, chatID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, chatID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserRepositoryMock_GetUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUser'
type UserRepositoryMock_GetUser_Call struct {
	*mock.Call
}

// GetUser is a helper method to define mock.On call
//   - ctx context.Context
//   - chatID int64
func (_e *UserRepositoryMock_Expecter) GetUser(ctx interface{}, chatID interface{}) *UserRepositoryMock_GetUser_Call {
	return &UserRepositoryMock_GetUser_Call{Call: _e.mock.On("GetUser", ctx, chatID)}
}

func (_c *UserRepositoryMock_GetUser_Call) Run(run func(ctx context.Context, chatID int64)) *UserRepositoryMock_GetUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *UserRepositoryMock_GetUser_Call) Return(_a0 *models.User, _a1 error) *UserRepositoryMock_GetUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UserRepositoryMock_GetUser_Call) RunAndReturn(run func(context.Context, int64) (*models.User, error)) *UserRepositoryMock_GetUser_Call {
	_c.Call.Return(run)
	return _c
}

// NewUserRepositoryMock creates a new instance of UserRepositoryMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserRepositoryMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserRepositoryMock {
	mock := &UserRepositoryMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
