// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	models "github.com/es-debug/backend-academy-2024-go-template/internal/domain/models"
	mock "github.com/stretchr/testify/mock"
)

// UserServiceMock is an autogenerated mock type for the UserService type
type UserServiceMock struct {
	mock.Mock
}

type UserServiceMock_Expecter struct {
	mock *mock.Mock
}

func (_m *UserServiceMock) EXPECT() *UserServiceMock_Expecter {
	return &UserServiceMock_Expecter{mock: &_m.Mock}
}

// DeleteUser provides a mock function with given fields: ctx, chatID
func (_m *UserServiceMock) DeleteUser(ctx context.Context, chatID int64) error {
	ret := _m.Called(ctx, chatID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = rf(ctx, chatID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UserServiceMock_DeleteUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteUser'
type UserServiceMock_DeleteUser_Call struct {
	*mock.Call
}

// DeleteUser is a helper method to define mock.On call
//   - ctx context.Context
//   - chatID int64
func (_e *UserServiceMock_Expecter) DeleteUser(ctx interface{}, chatID interface{}) *UserServiceMock_DeleteUser_Call {
	return &UserServiceMock_DeleteUser_Call{Call: _e.mock.On("DeleteUser", ctx, chatID)}
}

func (_c *UserServiceMock_DeleteUser_Call) Run(run func(ctx context.Context, chatID int64)) *UserServiceMock_DeleteUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *UserServiceMock_DeleteUser_Call) Return(_a0 error) *UserServiceMock_DeleteUser_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *UserServiceMock_DeleteUser_Call) RunAndReturn(run func(context.Context, int64) error) *UserServiceMock_DeleteUser_Call {
	_c.Call.Return(run)
	return _c
}

// GetUser provides a mock function with given fields: ctx, chatID
func (_m *UserServiceMock) GetUser(ctx context.Context, chatID int64) (*models.User, error) {
	ret := _m.Called(ctx, chatID)

	if len(ret) == 0 {
		panic("no return value specified for GetUser")
	}

	var r0 *models.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (*models.User, error)); ok {
		return rf(ctx, chatID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) *models.User); ok {
		r0 = rf(ctx, chatID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, chatID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserServiceMock_GetUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUser'
type UserServiceMock_GetUser_Call struct {
	*mock.Call
}

// GetUser is a helper method to define mock.On call
//   - ctx context.Context
//   - chatID int64
func (_e *UserServiceMock_Expecter) GetUser(ctx interface{}, chatID interface{}) *UserServiceMock_GetUser_Call {
	return &UserServiceMock_GetUser_Call{Call: _e.mock.On("GetUser", ctx, chatID)}
}

func (_c *UserServiceMock_GetUser_Call) Run(run func(ctx context.Context, chatID int64)) *UserServiceMock_GetUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *UserServiceMock_GetUser_Call) Return(_a0 *models.User, _a1 error) *UserServiceMock_GetUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UserServiceMock_GetUser_Call) RunAndReturn(run func(context.Context, int64) (*models.User, error)) *UserServiceMock_GetUser_Call {
	_c.Call.Return(run)
	return _c
}

// RegisterUser provides a mock function with given fields: ctx, chatID
func (_m *UserServiceMock) RegisterUser(ctx context.Context, chatID int64) error {
	ret := _m.Called(ctx, chatID)

	if len(ret) == 0 {
		panic("no return value specified for RegisterUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = rf(ctx, chatID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UserServiceMock_RegisterUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RegisterUser'
type UserServiceMock_RegisterUser_Call struct {
	*mock.Call
}

// RegisterUser is a helper method to define mock.On call
//   - ctx context.Context
//   - chatID int64
func (_e *UserServiceMock_Expecter) RegisterUser(ctx interface{}, chatID interface{}) *UserServiceMock_RegisterUser_Call {
	return &UserServiceMock_RegisterUser_Call{Call: _e.mock.On("RegisterUser", ctx, chatID)}
}

func (_c *UserServiceMock_RegisterUser_Call) Run(run func(ctx context.Context, chatID int64)) *UserServiceMock_RegisterUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *UserServiceMock_RegisterUser_Call) Return(_a0 error) *UserServiceMock_RegisterUser_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *UserServiceMock_RegisterUser_Call) RunAndReturn(run func(context.Context, int64) error) *UserServiceMock_RegisterUser_Call {
	_c.Call.Return(run)
	return _c
}

// NewUserServiceMock creates a new instance of UserServiceMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserServiceMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserServiceMock {
	mock := &UserServiceMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
